from . import *

global x

@hell_cmd(pattern="draid")
async def _(event):
    await eor(event, "stop raid")
    global x
    x = False


@hell_cmd(pattern="raid")
async def _(event):
    global x
    x = True
    while x == True:
        await event.delete()
        chat = event.chat_id
        await hellbot.send_message(chat, "AJA")
        await hellbot.send_message(chat, "TERI")
        await hellbot.send_message(chat, "MAA")
        await hellbot.send_message(chat, "KI CHUT")
        await hellbot.send_message(chat, "FAAD DUNGA")
        await hellbot.send_message(chat, "HIJDA SALA")
        await hellbot.send_message(chat, "BETE KALAP JAA")
        await hellbot.send_message(chat, "TERI MA KI CHUT ME STRANGER KA LAND")
        await hellbot.send_message(chat, "STRANGER OP TERE JAISE USKE LAND KI TOPI")
        await hellbot.send_message(chat, "BAAG JA BETE")
        await hellbot.send_message(chat, "TERA BAAP HU RANDI")
        await hellbot.send_message(chat, "TERA KHAANDAAN CHOD KE MMS BANAUNGA ")
        await hellbot.send_message(chat, "TERI BAHAN KO KOTHE PE CHODKE AAYA")
        await hellbot.send_message(chat, "TERE JAISE LANDU MERE LAND PE TEL LAGATE")
        await hellbot.send_message(chat, "BAHINCHOD SALA SUDHAR JA")
        await hellbot.send_message(chat, "KYU CHUDVAA RAHA APNI MAA KO BETA")
        await hellbot.send_message(chat, "HAM NAHI CHOD RAHE TERI MUMMY KO AB JAA")
        await hellbot.send_message(chat, "TERI BAHN KI CHUT KAALI KALI")
        await hellbot.send_message(chat, "SHIVANSH PAPA CHOD RAHA HAALI HAALI")
        await hellbot.send_message(chat, "BINA LAND KI TOPI")
        await hellbot.send_message(chat, "NALAYAK BETE")
        await hellbot.send_message(chat,  "BAAP HI TUMHARA")
        await hellbot.send_message(chat, "SUNAA HAI TERI MUMMY MUJHE BHATAAR BOLTI")
        await hellbot.send_message(chat, "TUJHE MAINE PAIDA KARKE GALTI TOH NAHI KI")
        await hellbot.send_message(chat, "MAT BHAUK BETE BAAP GUSSA HO JAYEGA TERA")
        await hellbot.send_message(chat, "TERI MAA KI")
        await hellbot.send_message(chat, "CHUT ME NIMBU DAAL KE ")
        await hellbot.send_message(chat, "TERI MAA KI CHUT KO KHAA JAUNGAAA") 
        await hellbot.send_message(chat, "MAAN JAA BETE NA BOL PAPA")
        await hellbot.send_message(chat, "KITNA BOLU YAAR KITNA BATAU") 
        await hellbot.send_message(chat, " MAINE TERI MAA KO CHODAA JARUR THAA PAR CONDOM KE SAATH")
        await hellbot.send_message(chat, "TU KISI HIJADE KI AULAAD")
        await hellbot.send_message(chat, "KALAP MAT BHOSADI KE PILLE")
        await hellbot.send_message(chat, "TERI BAHAN KA BABU HU ")
        await hellbot.send_message(chat, " FIGHT SE PAHLE APNI MAA SE POOCHH TOHH LETA")
        await hellbot.send_message(chat,  "AB TERI MAAA KA KYA HOGAA ")
        await hellbot.send_message(chat, "AAAJ CHUDEGI BHI NAHI BECHARI")
        await hellbot.send_message(chat, "KYUKI TERE PAPA IDHAR BUSY")
        await hellbot.send_message(chat, "KOI NA TU JAANA TAB")
        await hellbot.send_message(chat, "UNGLI SE HI KAAM CHALA DENA CHUT ME DAAL KE APNE")
        await hellbot.send_message(chat, "MUMMY KO NIRAAS NA KARNA HO SAKE TOH PEL DENA")
        await hellbot.send_message(chat,  "AB CHALA JAA MUJHE HIJDO SE")                                                     
        await hellbot.send_message(chat, "NAAA BAAT KARNI")
        await hellbot.send_message(chat, "BETE NIKL AAA PAPA KO SONE DE")
        await hellbot.send_message(chat, "BAAAP SE BAAKCHODI")
        await hellbot.send_message(chat, "KAREGAAA SUAR")
        await hellbot.send_message(chat, "KE PILLE TERI MAA")
        await hellbot.send_message(chat, "KI CHUT")
        await hellbot.send_message(chat, "BETA CHUSS LE MERA")
        await hellbot.send_message(chat, "LAND AUR BAAG JAA")
        await hellbot.send_message(chat, "TERI MAA KI BOOBS OP HAI")
        await hellbot.send_message(chat, "TERI BAHAN KA CHUT THODA DHEELI")
        await hellbot.send_message(chat, "BODY TONAR MANGA DE USKE LIYE SUDOL HO JAYEGA")
        await hellbot.send_message(chat, "TERI BUAA KO CHODU GAANE ME LE JAAKE KE")
        await hellbot.send_message(chat, "RANDU KAA PILLLA")
        await hellbot.send_message(chat, "BAAAP BAAAP HOTA HAI GAAND MAAR LEGAAA")
        await hellbot.send_message(chat, "MERE LAND")
        await hellbot.send_message(chat, "KE UPAR KE KAALE BAAL")
        await hellbot.send_message(chat, "SAALA BAAP SE UCHHALTAA")
        await hellbot.send_message(chat, "MAT BHOOL SHIVANSH TERE PAPA HAI")
        await hellbot.send_message(chat, "KITANA PELU YAAR LAND ME DARD")
        await hellbot.send_message(chat, "MERA LAND MUH ME RAKH LE AUR BAAG JAA")
        await hellbot.send_message(chat, "KOI HOGA TERE JAISE JO MUJHE PAPA BOLEGA TU RAHNE DE")
        await hellbot.send_message(chat, "NIKL JAA SALE")
        await hellbot.send_message(chat, "LAND LE LE MERA")
        await hellbot.send_message(chat, "CHALA JA BHOSADIKE")
        await hellbot.send_message(chat, "HAA HAA JAA APNE BAAP KO MAT")
        await hellbot.send_message(chat, "SHIKHAA")
        await hellbot.send_message(chat, "TERI MAA RANDI TOH SABKO NA BTA")
        await hellbot.send_message(chat, "CHAL BTA MERA LAND KAISA THA")
        await hellbot.send_message(chat, "JAB MUH ME RAKHA THA TERE BAHUT KHUSH HUA TU")
        await hellbot.send_message(chat, "MAAN GYAAA TERA KHAAN DAAN BAHUT CHUDAKKAD")
        await hellbot.send_message(chat, "LAUDEE")
        await hellbot.send_message(chat, "CHUT KE BAAL")
        await hellbot.send_message(chat,  "BETE PAPA BOL")
        await hellbot.send_message(chat, " BAAG RANDI")
        await hellbot.send_message(chat, "NIKAL LAUDE")
        await hellbot.send_message(chat, "SO JAA DUDH PEE KE")
        await hellbot.send_message(chat, "BABY MAAT RO MILEGA LAND")
        await hellbot.send_message(chat, "TUJHE CHODD KE ARAAM MILA")
        await hellbot.send_message(chat, "TERE JAISE LOG MERE LAND PE") 
        await hellbot.send_message(chat, " JHOOL RAHE RASSSI DALKE")
        await hellbot.send_message(chat, "TU NA SAH PAYEGA BABU MUMMY KO BHEJ") 
        await hellbot.send_message(chat, "MERA LAND AUR DIL DONO BADAA")
        await hellbot.send_message(chat, "PAHLE APNE DIDI KO BHEJ DIL ME PHIR LAND ")
        await hellbot.send_message(chat, "YE KHUDAA TU APNI MAA CHUDAA")
        await hellbot.send_message(chat, "MAAN JAA BABU NA CHUDAA KHUD KO")
        await hellbot.send_message(chat, "HIJADE KI AULAAAD")
        await hellbot.send_message(chat,  "TERE MUMMY KO KUTTA BHI NA CHHODE")
        await hellbot.send_message(chat, "TU HARAMI NAHI NAJAYAJ HAI")
        await hellbot.send_message(chat, "TERI BAHAN KA FUDDDI BECHUUU")
        await hellbot.send_message(chat, "AAA MERAA LANDDD CHUUS")
        await hellbot.send_message(chat, "TERI BIBI KO KUTTA CHODEEE")
        await hellbot.send_message(chat, "TERI MAA MERI BANDII")
        await hellbot.send_message(chat,  "TU SUDHAAR JAAA BETE")                                                     
        await hellbot.send_message(chat, "TERI MAAA KA HENDEL MAAARU")
        await hellbot.send_message(chat, "JHAAT KE BAAL")
        await hellbot.send_message(chat, "SUAAR KA PILLA")
        await hellbot.send_message(chat, "RANDI")
        await hellbot.send_message(chat, "SAADI HUII GAAND")
        await hellbot.send_message(chat, "TERI MAA KO BAJAAR ME NANGAA CHODUUU")
        await hellbot.send_message(chat, "CHHIPKAALI KI CHUT")
        await hellbot.send_message(chat, "PAHCHANA SHIVANSH PAPA HU")
        await hellbot.send_message(chat, "AAJA BETE")
        await hellbot.send_message(chat, "PAPA NA BOL BAAP BOL")
        await hellbot.send_message(chat, "TERI MAA MERE LAND SE HI CHUDEGI")
        await hellbot.send_message(chat, "TU KITNA BADA GANDU HAI")
        await hellbot.send_message(chat, "😈 TERI MAAA KI CHUT KO BECH KE COCO KOLA PIUNGAA")
  
                
        
        CmdHelp("raid").add_command(
    "raid", None, "Big Gaali Spam!"
).add_command(
    "draid", None, " spam stop!"
).add_warning(
    "May get floodwait!"
).add_info(
    "Spammer Module"
).add()
        
 
